[package]
name = "test"
version = "0.1.0"
edition = "2024"

[dependencies]
spider = "2.37.159"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
